### ISSUE TITLE
Troubleshooting OS tabs should be syncronized

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-dashboard#10]
Changing tab from `Linux` to `macOS` should alter all the tab instances.

![Screenshot 2021-03-10 at 17 17 00](https://user-images.githubusercontent.com/7974813/110661068-7b788080-81c4-11eb-950e-404b9e5e0f1d.png)

**Comment by matmertz25** [comment]
Im not quite sure how to implement this without using some higher level state management store like redux. 

Since these components can be quite nested and at very different points in the DOM im not quite sure how to cleanly sync the state of all these up. Any thoughts on how to best do this?

**Comment by matmertz25** [comment]
#4 I added some initial local OS detection but not quite sure about syncing these elements

**Comment by vojtechsimetka** [comment]
> Im not quite sure how to implement this without using some higher level state management store like redux.

React has something called [Context API](https://reactjs.org/docs/context.html) which can be used exactly for this. Feel free to try it or I can implement it :)
