### ISSUE TITLE
Connection failures

### ISSUE THREAD

**Issue by cagdasdoner** [ethersphere/bee-dashboard#100]
I an trying to access to my node remotely by updating the host from localhost to mu server IP. Even I can navigate to MY_SERVER_IP:1635/settlements address and see stats in JSON, but dashboard cannot connect. Is there a generic bug or I need to check my setup ?

**Comment by vojtechsimetka** [comment]
Hi, do you have CORS enabled? Is there anything in the browser developer console?

**Comment by cagdasdoner** [comment]
You're right, it is CORS. 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:1633/. (Reason: CORS request did not succeed).

How can I enable it ?

thanks.

**Comment by agazso** [comment]
Check that the following lines are in your Bee config file and restart your Bee node:
```
debug-api-enable: true
cors-allowed-origins: "*"
```

Please be aware that these settings allow any webpage to connect to your Bee node and the Debug API.

**Comment by matmertz25** [comment]
@cagdasdoner  see the following issue for more detail on configuring CORS. https://github.com/ethersphere/bee-dashboard/issues/94#issuecomment-834773708, it is also possible to put your IP address into the allowed origins to be safer and avoid anyone from being able to access your bee node API

**Comment by cagdasdoner** [comment]
Thanks pals! they are all working now. I'll also test with bee release 0.6.0.
