### ISSUE TITLE
Network protocol violation

### ISSUE THREAD

**Issue by hippalectryon-0** [ethersphere/bee-dashboard#102]
On firefox 88.0.1, windows 10:

Right after installing, running `bee-dashboard` opens http://localhost:8080/, which shows "The site at http://localhost:8080/ has experienced a network protocol violation that cannot be repaired."

The only line in the developer console is "No strings exist for error: corruptedContentErrorv2-title".

**Comment by vojtechsimetka** [comment]
Thanks for reporting this

**Comment by vojtechsimetka** [comment]
This should be solved by #122
