### ISSUE TITLE
Problem to access tot he UI and some doubts about dockerize bee dashboard

### ISSUE THREAD

**Issue by tropicar** [ethersphere/bee-dashboard#103]
HI, am a DAppNode developer i am trying to dockerize the bee-dashboard for including on the bee package.
I Created this Dockerfile

`FROM node:15.6-buster-slim 

WORKDIR /usr/src/app

RUN apt-get update && \ 
    apt-get install -y g++ build-essential && \
    npm install -g @ethersphere/bee-dashboard 

ENTRYPOINT [ "bee-dashboard" ]`

I executed with: 
`docker run -dp 127.0.0.1:8080:8080 Container`

But I can't access the UI. 
I tried to access using the IP of the container but I can't either. Do I forget to execute something or some flag?

On the log of the container, they are normal:
`> Executing task: docker logs --tail 1000 -f d29e362765cfdebc50f0b43428e458db56282ae6243d8d4d95bcb53f61c32ef5 <

Starting up Bee Dashboard on address http://localhost:8080
Hit CTRL-C to stop the server
^C
Terminal will be reused by tasks, press any key to close it.`

Then I tried to use the Development installation on my laptop, but I have this issue https://github.com/ethersphere/bee-dashboard/issues/98 .

The main questions are:
1- Do i have to add some flag or something to be able to access to the UI?
2. If you have running bee in docker and dashboard-bee in another docker, should it be work?

**Comment by vojtechsimetka** [comment]
Hi @tropicar . To answer your questions:

> 1. Do i have to add some flag or something to be able to access to the UI?

No it should work out of the box. Just a reminder you need to build the project and then serve it somehow (basically everything you need is in the `./build` folder).

> 2. If you have running bee in docker and dashboard-bee in another docker, should it be work?

I have not tried it myself, not really a heavy docker user but there is this PR that might do what you want https://github.com/ethersphere/bee-dashboard/pull/75 . We have been busy with new bee release and update of the whole ecosystem about it, but next week I'd look into this.

**Comment by vojtechsimetka** [comment]
Closing as the docker file was merged #75. For support please contact the team through Discord.
