### ISSUE TITLE
Could not connected to Bee node with Bee 0.6.0

### ISSUE THREAD

**Issue by litcloud** [ethersphere/bee-dashboard#107]
Hi, 

Recently I installed Bee 0.6.0 on Ubuntu 20.04 and I should have successfully made Bee running with command "systemctl status bee". But bee-dashboard says "Could not connect to Bee Node". Any advises?

**Comment by vojtechsimetka** [comment]
Hi, do you have CORS set up on the Bee node? It is part of the troubleshooting section. See https://github.com/ethersphere/bee-dashboard/issues/94#issuecomment-834773708

**Comment by litcloud** [comment]
I just checked #94(comment) but found the URLs are invalid. Any more advises?

**Comment by litcloud** [comment]
I tried modifying bee.yaml in the line with "cors-allowed-origins" by changing the original "[]" to * or 127.0.0.1 or http://localhost but none of them works.

**Comment by 1058745043** [comment]
Me too.

**Comment by yoseeX** [comment]
I also encountered this problem, I cloned the project via https, and my bee version is 0.61

**Comment by litcloud** [comment]
I updated bee to 0.6.2 and update bee-dashboard to the latest version, which should support bee 0.6.0, but the problem remains.

**Comment by yoseeX** [comment]
> 我把bee更新到0.6.2，把bee-dashboard更新到最新版本，应该支持bee 0.6.0，但问题依旧。

Try to replace [] with ["*"]

**Comment by litcloud** [comment]
> > I updated bee to 0.6.2 and update bee-dashboard to the latest version, which should support bee 0.6.0, but the problem remains.
> > Try to replace [] with ["*"]

Many thx, after replacing with ["*"], it works now, closing this issue.
