### ISSUE TITLE
Mac troubleshooting steps provide invalid command

### ISSUE THREAD

**Issue by Zaphod101010** [ethersphere/bee-dashboard#109]
I'm trying to troubleshoot why bee-dashboard is unable to connect to my bee node.

Step 1 is: Check the status of your node by running the below command to see if your node is running.

`brew services status swarm-bee`

That command returns: `Error: Invalid usage: unknown subcommand: status`

Maybe the troubleshooting command here should be `brew services list`?

**Comment by vojtechsimetka** [comment]
Nice catch, thank you! We could also use just `brew services` :) Want to give it a try and create PR?
