### ISSUE TITLE
Starting up Bee Dashboard on address http://localhost:8080 How to use other hosts to access?

### ISSUE THREAD

**Issue by z724133545** [ethersphere/bee-dashboard#110]
Starting up Bee Dashboard on address http://localhost:8080 How to use other hosts to access? 
My bee is running in CentOS. I want to access the dashboard on another host.

**Comment by matmertz25** [comment]
There are 2 things that need to be done to access your bee node from a remote host. 

1. Edit configuration file and restart bee node

   a. Enable CORS for your host
https://docs.ethswarm.org/docs/working-with-bee/configuration#--cors-allowed-origins
Edit the above  **cors-allowed-origins*** parameter in your bee nodes configuration file to include the host by which you want to access the dashboard from (your computers IP); OR you can "*" this parameter to allow any  IP address to access the bee node but using this method should also include blocking with a firewall setting to not allow any computer to access private bee node APIs

   b.  Make sure your bee node is broadcasting on the machines public IP and the debug endpoint is enabled. 

```
cors-allowed-origins: ['127.0.0.1'] <--- add the IP from which you want to allow access or "*"
p2p-addr: :1634
debug-api-addr: :1635
debug-api-enable: true
```


2. Once bee dashboard has been started you must change the host addresses in either the settings or status page

**Comment by z724133545** [comment]
Thank you for your answer

> 要从远程主机访问您的蜂节点，需要完成两件事。
> 
> **1.编辑配置文件并重新启动bee节点**
> 
> 一种。为您的主机启用CORS
> 
> https://docs.ethswarm.org/docs/working-with-bee/configuration#--cors-allowed-origins在蜜蜂节点配置文件中
> 编辑上述 **cors-allowed-origins**参数，以包括您要使用的主机从（您的计算机IP）访问仪表板；或者，您可以“ *”此参数以允许任何IP地址访问蜂节点，但使用此方法还应包括使用防火墙设置进行阻止，以禁止任何计算机访问私有蜂节点API
> 
> b。确保您的bee节点正在计算机公用IP上广播，并且调试端点已启用。
> 
> C。重新启动蜂节点https://docs.ethswarm.org/docs/FAQ#what-are-the-restart-commands-of-bee
> 
> ```
> cors-allowed-origins: ['75.185.00.00']  # <--- add the IP from which you want to allow access or "*"
> api-addr: :1633
> debug-api-addr: :1635
> debug-api-enable: true
> ```
> 
> **2.蜂仪表板启动后，您必须在设置或状态页面中更改主机地址。**
> 
> 有关使用设置页面进行编辑的信息，请参见下文
> 
> ![](https://raw.githubusercontent.com/ethersphere/bee-dashboard/master/ui_samples/settings.png)

Thank you for your answer

**Comment by vojtechsimetka** [comment]
Hi @z724133545 , this is not currently user configurable but there is an issue with this being a feature request already #112 . If you do want to serve it on a different host yourself, the best way is to download the files from git, build the project and serve it with any http server. So you build the project

```
git clone git@github.com:ethersphere/bee-dashboard.git
cd bee-dashboard
npm ci
npm run build
```

And serve the `./build` folder with any http server you want. You can also use the `http-serve` we are using, just edit the configuration https://github.com/ethersphere/bee-dashboard/blob/aab0462047a3fcd87ba258b5486aede922865b1e/serve.js#L12-L16
