### ISSUE TITLE
Feature Request: Add option to change port

### ISSUE THREAD

**Issue by Zaphod101010** [ethersphere/bee-dashboard#112]
Port 8080 is hard coded.  I already have another server running on port 8080.

I'd like to be able to manually change the port bee-dashboard runs on.

It would be great if it could also do some checks on startup to see if port 8080 is already in use, then increment the port by 1 until it finds an available port.

**Comment by vojtechsimetka** [comment]
Thanks @Zaphod101010 for the suggestion. It makes sense but is not currently our priority. If anyone wants to try and implement it I'll promise to review timely :).

In the meantime, if someone wants to run the project on a different port, the easiest way is to do following is to download the files from git, build the project and serve it with any http server.

```
git clone git@github.com:ethersphere/bee-dashboard.git
cd bee-dashboard
npm ci
npm run build
```

And serve the `./build` folder with any http server you want. You can also use the `http-serve` we are using, just edit the configuration https://github.com/ethersphere/bee-dashboard/blob/aab0462047a3fcd87ba258b5486aede922865b1e/serve.js#L12-L16
