### ISSUE TITLE
bee-dashboard list

### ISSUE THREAD

**Issue by wuxkui** [ethersphere/bee-dashboard#118]
bee-dashboard  : no  list

**Comment by vojtechsimetka** [comment]
Hi, I don't understand what is your issue, can you please explain it better?

**Comment by wuxkui** [comment]
This instrument , no list , no batch add IP:port

**Comment by wuxkui** [comment]
provide an account ,api list show?

**Comment by wuxkui** [comment]
whether or not  bee 1633/1635 API list -show ?

**Comment by vojtechsimetka** [comment]
Please follow the install and usage guide from README. You will have to enable CORS and Debug API on bee https://github.com/ethersphere/bee-dashboard#usage
