### ISSUE TITLE
Show if the Bee node is lightnode or fullnode

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-dashboard#128]
This is currently not possible as there is no API which would detect if Bee node is started as lightnode or fullnode.

**Comment by agazso** [comment]
Related: https://github.com/ethersphere/bee/issues/1668

**Comment by vojtechsimetka** [comment]
The info endpoint has been added to Bee and we can now implement this feature https://bee-js.ethswarm.org/docs/api/classes/beedebug/#getnodeinfo . The existing dev mode flag could be removed.

**Comment by vojtechsimetka** [comment]
implemented in #318
