### ISSUE TITLE
how to run dashboard as daemon

### ISSUE THREAD

**Issue by ferdiina** [ethersphere/bee-dashboard#130]
how to run dashboard as daemon
install via npm

**Comment by vojtechsimetka** [comment]
Thank you for the suggestion. This is out of scope for the Bee Dashboard as our aim is to go more towards desktop app.

However, to not leave you dry, the easiest option is to serve the `build` folder with for example `nginx`. Here is a decent tutorial on how to do it https://blog.devgenius.io/using-nginx-to-serve-react-application-static-vs-proxy-69b85f368e6c .
