### ISSUE TITLE
Something is wrong when deploy 0.3.0

### ISSUE THREAD

**Issue by youxiaohou** [ethersphere/bee-dashboard#136]
How to fixed this problem? Ubuntu 20.04

![image](https://user-images.githubusercontent.com/82362675/120587348-c292ac80-c467-11eb-82a1-ce99ca6c993c.png)

**Comment by vojtechsimetka** [comment]
Hi, thanks for reporting this. I'll provide a fix we will release new version.

**Comment by youxiaohou** [comment]
ok , thank you a lot

**Comment by vojtechsimetka** [comment]
Please use the `0.3.1` version which should have this resolved.
