### ISSUE TITLE
Run on windows 10

### ISSUE THREAD

**Issue by nakroy** [ethersphere/bee-dashboard#142]
I downloaded the code , but it seems not support for windows 10 system .

**Comment by joln** [comment]
it running good for my win10 system.See this link: 
http://github.com/ethersphere/bee-dashboard/issues/94#issuecomment-834773708

**Comment by nakroy** [comment]
Thanks for your reply , I'm going to have a try , have a good day!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ethersphere/bee-dashboard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月5日(星期六) 上午8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ethersphere/bee-dashboard] Run on windows 10 (#142)





 
it running good for my win10 system.See this link:
 http://github.com/ethersphere/bee-dashboard/issues/94#issuecomment-834773708

**Comment by nakroy** [comment]
Sir, if I want to add more nodes to manage ,what should I do ?

**Comment by nakroy** [comment]
And I can open localhost:8080 on Edge , but when I set firefox as my default browser ,  it turns out "Acess Error :404--Not Found" on firefox

**Comment by agazso** [comment]
> Sir, if I want to add more nodes to manage ,what should I do ?

Currently with the Bee Dashboard you can manage one node at a time. You can change the address of the node in the Status / Node setup or in the Settings tab.

For managing more than one node there is the [Beekeeper project](https://github.com/ethersphere/beekeeper) however it works in the command line and assumes familiarity with Geth and Kubernetes too.

**Comment by nakroy** [comment]
> 
> 
> > Sir, if I want to add more nodes to manage ,what should I do ?
> 
> Currently with the Bee Dashboard you can manage one node at a time. You can change the address of the node in the Status / Node setup or in the Settings tab.
> 
> For managing more than one node there is the [Beekeeper project](https://github.com/ethersphere/beekeeper) however it works in the command line and assumes familiarity with Geth and Kubernetes too.

Fine, I more like user-friendly-UI, it's more convenient to use .
