### ISSUE TITLE
cluster support

### ISSUE THREAD

**Issue by Zhangxh1011** [ethersphere/bee-dashboard#147]
one: Can we use one tool for multi-node management ，The deployment and maintenance of K8s are also more complicated
two：Whether each node after bee must use a public network address？If yes, how to maintain it in the future

**Comment by vojtechsimetka** [comment]
Thanks for the suggestion. Please see this response https://github.com/ethersphere/bee-dashboard/issues/135#issuecomment-853570533

Closing as a duplicate.
