### ISSUE TITLE
Add health indicator to depth / population/ connected peer count

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-dashboard#15]
In the `peers` page there are currently metrics for population, connected peer count and depth as just numbers. These are interesting for advanced user, but most users will have no idea what that means and what are "good numbers".

The task is to also add an indicator that would show whether these values are as expected and ideally provide some broader context (without overwhelming the user)

**Comment by matmertz25** [comment]
Agree, this is definitely something that makes sense to implement. I would defer to others on the swarm team though to decide on what "good" or "healthy" numbers are as i'm not sure how to best represent those levels.
