### ISSUE TITLE
Status text "Could not connect to Bee Node" is sometimes misleading

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee-dashboard#168]
I have a running Node without peers.

<img width="376" alt="Screenshot 2021-08-12 at 13 45 00" src="https://user-images.githubusercontent.com/77121044/129191595-d03189f3-d4fd-4fcf-b46b-b330d60a8302.png">

Since the peer check fails, it shows that I am not connected to my node.

<img width="448" alt="Screenshot 2021-08-12 at 13 45 11" src="https://user-images.githubusercontent.com/77121044/129191627-7584a1b3-5515-4d92-865d-5f9a8b9f7f1c.png">

If any of the checks fail, we display this error message.

```
isOk={checks.every(c => c.isOk)}
```

It may be better to fine-tune it for some of the edge cases like this (by providing more accurate messages).

**Comment by agazso** [comment]
I agree that it would be better to change the text to "There is a problem with your node configuration" or something similar.

When this happen is it only a text that is displayed or there is also a change in behaviour?

**Comment by Cafe137** [comment]
No other side effects I noticed
