### ISSUE TITLE
Deployed and funded chequebook ERROR

### ISSUE THREAD

**Issue by ahmeria** [ethersphere/bee-dashboard#193]
Hi,
I installed bee-dashboard. In status tab, in node setup division only one unchecked. Deployed and funded chequebook. In details it says "Your chequebook is either not deployed or funded." What should i do?

**Comment by vojtechsimetka** [comment]
HI @ahmeria , thank you for creating the issue. Which version of `bee-dashboard` and `bee` are you running? Do you have address of the chequebook or at least of your bee node eth address? With this information we could look at the blockchain if it is really deployed and funded.

**Comment by ahmeria** [comment]
Hello,

 

Versions:

Bee-dashboard : 0.7.0

Bee: 1.1.0

 

Addresses:

Chequebook: 0xF5be1283C534E137Ef97D6b5277f8C5B8AA9c0F1

Eth: 0xfb7948713f3083a090b3ce6f6ea80f2b44006ebb

 

Can you check it? Thanks

**Comment by vojtechsimetka** [comment]
So neither of these addresses has any BZZ balance = the error you are seeing is correct.

This is a chequebook with some token balance: https://blockscout.com/xdai/mainnet/address/0xb30347c3A847102fcbDb43B3F15D07a8aa51Ad49/tokens

This is yours: https://blockscout.com/xdai/mainnet/address/0xF5be1283C534E137Ef97D6b5277f8C5B8AA9c0F1/tokens


That being said, we currently don't support running bee in lightnode (which does not require chequebook nor xBZZ balance). Are you running bee node in lightnode? You can find out in the bee config file.
