### ISSUE TITLE
Style of the error state for the node status button

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-dashboard#196]
In the PR #194 this button does not have proper non-selected error state

Current look:
![Screenshot 2021-08-31 at 10 01 13](https://user-images.githubusercontent.com/7974813/131465694-11812693-3bff-44a3-aa8a-c907b9cf684f.png)

Should be:
![Screenshot 2021-08-31 at 9 37 26](https://user-images.githubusercontent.com/7974813/131462732-d91b80a7-430f-4ce9-a008-a51ee22a39dc.png)

The selected state is correctly implemented
Current look:
![Screenshot 2021-08-31 at 10 01 08](https://user-images.githubusercontent.com/7974813/131465712-24aa1a1d-3aea-4faf-89ca-c1b2591b6d09.png)

Reference:
![Screenshot 2021-08-31 at 9 37 31](https://user-images.githubusercontent.com/7974813/131462851-7b1489d2-4ee3-4f16-afb3-b7fde3dabcf8.png)

**Comment by Cafe137** [comment]
@vojtechsimetka can this be closed? 🙂
