### ISSUE TITLE
Desktop app name on macOS

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-dashboard#212]
The application name should be Bee Dashboard (as in the title of the window) in the menubar and the menu as well. The icon could be the swarm logo (in black with transparent background).

<img width="1440" alt="Screenshot 2021-10-05 at 10 44 43" src="https://user-images.githubusercontent.com/230163/135993449-18f3bdaf-23b0-490f-8dc7-cc03756ad2d1.png">

**Comment by vojtechsimetka** [comment]
Closing this as we are moving forward with a dedicated bee-desktop app in a separate repo.
