### ISSUE TITLE
Having no peers connected should not prevent users to interact with their bee node

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-dashboard#241]
Maybe we should introduce some orange state and not prevent interactions if the bee node has no peers. At minimum this is good for development, you can just run one bee node and don't have to wait for the peers to be connected.
![Screenshot 2021-11-12 at 8 29 47](https://user-images.githubusercontent.com/7974813/141428096-92b14ab5-6c55-4a81-8396-d918dc00d632.png)
![Screenshot 2021-11-12 at 8 30 00](https://user-images.githubusercontent.com/7974813/141428105-8cd2eae2-e310-478c-adb8-f546e97945b8.png)

**Comment by agazso** [comment]
I agree that this should not be a blocker. Once you have connection to your node (or even the debug API) it would be good if you could access the tabs, maybe with the actions disabled.
