### ISSUE TITLE
Status screen has green items even there is no connection

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-dashboard#309]
The status screen reports that `Chequebook Deployment & Funding` and `Connection to Peers` are green even though there is no connection to Debug API and Bee API. In these cases it would be better to show all red.
<img width="1431" alt="Screenshot 2022-03-14 at 12 41 37" src="https://user-images.githubusercontent.com/230163/158165438-5b117df3-6c9e-4e1f-8b65-d9b8575d5d65.png">

**Comment by vojtechsimetka** [comment]
This is because you had dev mode enabled through the environment variable. This gets fixed by #318
