### ISSUE TITLE
Cannot buy stamp with space in the label

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-dashboard#326]
I cannot buy a stamp if there is space or other special characters (like dash) in the label field, the button becomes disabled. I am not sure where this limitation comes from. 

If there is a limitation for label names in Bee then it would be good to display a warning with an explanation of what is an allowed label name. Or alternatively we could only allow those characters in the field which make up valid label names.

**Comment by vojtechsimetka** [comment]
Actually this is already the case. Maybe you were running some older version?

See the label regex check https://github.com/ethersphere/bee-dashboard/blob/master/src/pages/stamps/PostageStampCreation.tsx#L115
and the `!isValid` check on the button https://github.com/ethersphere/bee-dashboard/blob/master/src/pages/stamps/PostageStampCreation.tsx#L150

<img width="1241" alt="Screenshot 2022-04-24 at 14 55 34" src="https://user-images.githubusercontent.com/7974813/164971041-2ee3d7de-d5cf-4dad-9c6e-6b01a7b056bb.png">

**Comment by vojtechsimetka** [comment]
But I did discover that the form sometimes updates only after you de-focus the input field. I could investigate that.
