### ISSUE TITLE
Missing files/directories when uploading website

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-dashboard#363]
Originally reported by @jpritikin here https://github.com/ethersphere/swarm-extension/issues/106

**Comment by vojtechsimetka** [comment]
@jpritikin I would love to follow up on this bug:

1. Do you have the folder you tried to upload? I would love to try it myself for debugging purposes.
2. Did you try and use a drag and drop? Is the problem the same?
3. Would you happen to know the version of swarm-extension that you are using?

**Comment by jpritikin** [comment]
> Do you have the folder you tried to upload? I would love to try it myself for debugging purposes.

Download from [here](https://drive.google.com/file/d/1QXwG1tu80toSLkxMtl57yS1_26XAaYjD/view?usp=sharing)

> Did you try and use a drag and drop?

Hm, no, but I tried now and it seems that drag and drop doesn't work. Nothing happens. I use Ubuntu 22.04 with google chrome 101.0.4951.41

> Would you happen to know the version of swarm-extension that you are using?

I'm using whatever is bundled with the swarm extension v0.3.0. I see `"@ethersphere/bee-dashboard": "^0.14.0",` in the `package.json` but I'm not sure if that's helpful.

**Comment by vojtechsimetka** [comment]
Oh I see the problem, it actually flattens the `static` folder. We'll fix this, thanks for reporting! :)

**Comment by jpritikin** [comment]
Wow, great!

**Comment by jpritikin** [comment]
Thanks for the v0.3.1 release.
