### ISSUE TITLE
Websites still don't get uploaded properly

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-dashboard#427]
@agazso please provide more info

**Comment by agazso** [comment]
Here is an example website that can demonstrate the issue:
[example-website.zip](https://github.com/ethersphere/bee-dashboard/files/8956123/example-website.zip)

The file has the following structure:
```
/index.html
/assets/1.png
/assets/2.png
```

Upload the example website that is attached in a zip file. It returns `32fa04094dedb192ff10f62747f2aaf99bdb458e491605d845a52f45561a3b43` as swarm reference.


However if you check it in `swarm-cli` you can see it flattens the folders:
```
% swarm-cli manifest list 32fa04094dedb192ff10f62747f2aaf99bdb458e491605d845a52f45561a3b43
1dce244842de4dd7556e2a63226cc4c07d0912fdaf6cf1792cb5b390c56f2739 /.swarmgatewaymeta.json
85c87f779ab70e55bd742113ba1e6dced3a024cf4eec2974ba049254b99f412a /1.png
196f2b09932f60747f30b9d10faef7d08306634ac76d2dfe9e31093fa1c18b9a /2.png
ee5a4abb00f7ad377be9cf3c986fe270a35da87c2a1b09c1f3d9dda769755049 /index.html
```

If you upload the same website on the gateway it returns a different reference: `535e86d744da9615a965fc4e4309eb0be9a71f8bf6460a4ac1a38d8fb7180942`

Listing that shows the correct folder structure:
```
% swarm-cli manifest list 535e86d744da9615a965fc4e4309eb0be9a71f8bf6460a4ac1a38d8fb7180942
1dce244842de4dd7556e2a63226cc4c07d0912fdaf6cf1792cb5b390c56f2739 /.swarmgatewaymeta.json
85c87f779ab70e55bd742113ba1e6dced3a024cf4eec2974ba049254b99f412a /assets/1.png
196f2b09932f60747f30b9d10faef7d08306634ac76d2dfe9e31093fa1c18b9a /assets/2.png
ee5a4abb00f7ad377be9cf3c986fe270a35da87c2a1b09c1f3d9dda769755049 /index.html
```
