### ISSUE TITLE
Swapping XDAI to BZZ ignores the amount

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-dashboard#431]
Reported by `pepesza` on [Discord](https://discord.com/channels/799027393297514537/988743474398502992/989150581228703754):

> when upgrading the node from ultra-light to light, there is a possibility to do that with xdai. First step is depositing xdai to wallet. Second is swapping some of deposited xdai to bzz. This second step ignores changes to default amount of bought bzz. Edit: I'm using Firefox, mentioning that as potentially relevant detail

**Comment by Cafe137** [comment]
This was fixed in https://github.com/ethersphere/bee-dashboard/pull/448
