### ISSUE TITLE
If upgrade fails, user can not trigger it again when they have some balance

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-dashboard#442]
![Screenshot 2022-06-27 at 14 19 02](https://user-images.githubusercontent.com/7974813/175939549-d550be02-f00e-4590-9728-d49d421699dd.png)
![Screenshot 2022-06-27 at 14 19 11](https://user-images.githubusercontent.com/7974813/175939567-d4df46bd-229e-498e-a020-6fd8312685bb.png)

**Comment by vojtechsimetka** [comment]
Right, but I have funding and everything so I should just be able to click some button somewhere.

**Comment by agazso** [comment]
Hmm, that's true.

We need to redesign this. As a workaround we may add some text and a button to the Top-up page, centered, below the funding buttons.
Text: `Your node is funded and ready to be upgraded to light mode.`
Button: `Upgrade & restart`

What do you think?

**Comment by vojtechsimetka** [comment]
Sounds good!
