### ISSUE TITLE
Files with emdash in their names cannot be uploaded

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-dashboard#474]
Unfortunately the error notification does not tell much either (related #473). Possibly other names with funny characters in it may fail.

<img width="1379" alt="Screenshot 2022-07-05 at 18 09 34" src="https://user-images.githubusercontent.com/230163/177373849-9a4932f8-b925-43db-9222-14a880219a1a.png">

**Comment by Cafe137** [comment]
Fixed by https://github.com/ethersphere/bee-dashboard/pull/491
