### ISSUE TITLE
RPC configuration from environment

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-dashboard#482]
Reported by [@mfw25 on Discord](https://discord.com/channels/799027393297514537/811574542069137449/995969005905002506):

> Hi all, just going through and having a look at bee-dashboard and doing some packaging for bee / bee-dashboard to run on dappnode.

> Everything is relatively straight forward, except the RPC configuration within bee-dashboard. Are there any environment variables that allow for setting a default RPC for bee-dashboard? This would be handy to set a default RPC, with the option available to override in the UI (store the override in a localstorage value).

**Comment by vojtechsimetka** [comment]
Implemented in #485
