### ISSUE TITLE
Entering * into amount when buying a postage stamp returns error

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/bee-dashboard#606]
Trying to enter an "*" into Amount field, returns an error. See screenshots.

![image](https://user-images.githubusercontent.com/1554520/215465247-ac953a0e-5598-4e67-8686-c3e2e0e693d8.png)

![image](https://user-images.githubusercontent.com/1554520/215465300-4d04fa2b-511b-4a92-97b1-be8225f32838.png)

Expected: just allow numbers to be entered?

**Comment by Cafe137** [comment]
This issue comes from PostageStampCreation.
