### ISSUE TITLE
I wouldn't mind if the settings'd bee similar to swarm desktop

### ISSUE THREAD

**Issue by tamas6** [ethersphere/bee-dashboard#607]
screenshot from desktop v
<img width="1168" alt="Screenshot 2023-02-03 at 19 23 03" src="https://user-images.githubusercontent.com/81620050/216678538-9048e027-387a-4b4e-b801-83a27f4b2aa3.png">

CORS allows
Data directory 
ENS resolver

Even if they are editable!!
missing from dashboard but if there's an apparent reason, pardon me

**Comment by Cafe137** [comment]
AFAIK Bee does not expose it through the API.
Desktop reads it from the filesystem, but the browser alone does not have this capability.

Can only be implemented without desktop if Bee exposes configs.
