### ISSUE TITLE
improve Topup and Dilute UI/UX

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee-dashboard#624]
![image](https://github.com/ethersphere/bee-dashboard/assets/520570/02cc4c19-d1a3-431a-8ea0-9688a6addbc1)

It is better from a UI/UX perspective to have two separate action buttons called "Topup" & "Dilute" instead of one action button "Topup & Dilute" considering that they are two very different actions from the user's perspective.

**Comment by Cafe137** [comment]
StampExtensionModal is a combined component that handles both topup and dilute.

Topup is for increasing the amount (TTL) of a stamp that already exists.
Dilute is for increasing the depth (capacity) of a stamp that already exists.

It would be better to properly separate these.
