### ISSUE TITLE
Stamp Labels are missing in the "Add postage stamp" page of update feeds

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee-dashboard#630]
![image](https://github.com/ethersphere/bee-dashboard/assets/520570/89587252-5622-449d-8adc-925d685cfe8c)
![image](https://github.com/ethersphere/bee-dashboard/assets/520570/a1f3fb66-03cb-4545-9459-69c6184a97ef)

**Comment by Cafe137** [comment]
This is in PostageStampSelector.

If a label is set on a stamp, it should show the label, and then the short hash in parantheses.
