### ISSUE TITLE
ununtu 18.04 intall error

### ISSUE THREAD

**Issue by yangchuang123456** [ethersphere/bee-dashboard#68]
Skipping 'fsevents' build as platform linux is not supported

> fsevents@1.2.13 install /home/ipfsmain/yc/project/bee-status/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

Skipping 'fsevents' build as platform linux is not supported
added 1929 packages in 11.001s

**Comment by agazso** [comment]
Thanks @yangchuang123456 !

It seems that this is just a warning and otherwise the install is working fine. Can you please confirm that this is the case?

**Comment by vojtechsimetka** [comment]
Closing as there is not activity. If this is still a problem please create new issue.
