### ISSUE TITLE
Add support for manage multiple nodes

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee-dashboard#71]
Currently only a single node is supported at time. This would be required also for #58

**Comment by vojtechsimetka** [comment]
Thanks @tmm360 this is an issue I wanted to make as well. The idea would be to have a state provider for each Bee node (#40 is the first step) and as an input into this context provider you could have the API and debug API url's.

As for #58, this button is per one node so it can even be implemented now. Simple filter on `accounting.filter(r => r.uncashed.toBigNumber.isGreaterThan(0))` gives you list of all peers which have some uncashed balance. Then the Cash all button just triggers cashout on each one of these peers.

`Accounting type`: https://github.com/ethersphere/bee-dashboard/blob/73702bfffba5ea88d3ba5039ba2d5e23c0e36231/src/hooks/accounting.ts#L7-L23
`accounting` array: https://github.com/ethersphere/bee-dashboard/blob/master/src/pages/accounting/index.tsx#L37

**Comment by vojtechsimetka** [comment]
closing in favour of #135 which is slightly clearer.
