### ISSUE TITLE
Windows Compatibiity?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee-dashboard#86]
Just tried to install this on Windows 10 and it appeared that the installation worked except for one error-ish looking thing on "npm run build":

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle bee-dashboard@0.1.0~prebuild: bee-dashboard@0.1.0
6 info lifecycle bee-dashboard@0.1.0~build: bee-dashboard@0.1.0
7 verbose lifecycle bee-dashboard@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle bee-dashboard@0.1.0~build: PATH: <snip>
9 verbose lifecycle bee-dashboard@0.1.0~build: CWD: D:\Swarm-Bee\bee-dashboard
10 silly lifecycle bee-dashboard@0.1.0~build: Args: [ '/d /s /c', 'react-scripts build' ]
11 silly lifecycle bee-dashboard@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle bee-dashboard@0.1.0~build: Failed to exec build script
13 verbose stack Error: bee-dashboard@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid bee-dashboard@0.1.0
15 verbose cwd D:\Swarm-Bee\bee-dashboard
16 verbose Windows_NT 10.0.19041
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error bee-dashboard@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the bee-dashboard@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

But the "npm run serve" still offered the local URL, but all that comes out in the browser is an "Index of build/" that shows favicon.ico, manifest.json, and robots.txt.

Any suggestions on what I can try to see what might be going worng (sic)?

**Comment by ldeffenb** [comment]
Just installed it under Ubuntu and it looks better:

=============
Compiled successfully.

File sizes after gzip:

  521.18 KB  build/static/js/2.9cddf069.chunk.js
  14.41 KB   build/static/js/main.a979ce4f.chunk.js
  1.57 KB    build/static/js/3.dd97f72a.chunk.js
  1.17 KB    build/static/js/runtime-main.820267dd.js
  549 B      build/static/css/main.2afbd7db.chunk.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

**Comment by vojtechsimetka** [comment]
Thank you for reporting this @ldeffenb . As we don't have that many windows users this is not our priority so any public contribution is welcome.
