### ISSUE TITLE
git clone https: vs git clone git@

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee-dashboard#87]
Tried cloning the repository on both Windows and Ubuntu using the git clone command from the readme:

  git clone git@github.com:ethersphere/bee-dashboard.git
  Cloning into 'bee-dashboard'...
  The authenticity of host 'github.com (140.82.112.3)' can't be established.
  RSA key fingerprint is 
  SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
  Are you sure you want to continue connecting (yes/no)? yes
  Warning: Permanently added 'github.com,140.82.112.3' (RSA) to the list of known hosts.
  git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.

but that failed on both platforms, but the following worked:

https://github.com/ethersphere/bee-dashboard.git

**Comment by vojtechsimetka** [comment]
Thank you for putting this forward. Yes git@github.com requires ssh token and using the http might be better. That being said I believe this issue will be resolved by #88 :)
