### ISSUE TITLE
300 max peers?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee-dashboard#89]
I have a DAppNode bee running that has 468 connected peers (ID starts with 0xf40...) in the /peers Debug API response.  But bee-dashboard is only showing 300 peers on the top of both the Status and Peers tabs and also only 300 in the Peers list.

Is this a limit in bee-dashboard or bee-js?

**Comment by vojtechsimetka** [comment]
Closing this as the peers tab has been removed. Not sure where the limit was, but bee-js returns all the peers so probably some bug in the code here.
